CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    privilege VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS sinister (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    identification VARCHAR(255) NOT NULL,
    gravity ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL
);

CREATE TABLE IF NOT EXISTS optional (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    value_location DECIMAL(10, 2) NOT NULL,
    value_declared DECIMAL(10, 2) NOT NULL,
    qtd_available INT NOT NULL
);

CREATE TABLE category (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    fine1To4Days DOUBLE NOT NULL,
    fine5To9Days DOUBLE NOT NULL,
    fine10DaysOrMore DOUBLE NOT NULL,
    createdAt TIMESTAMP NOT NULL
);